---
title: "Notes"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Meeting 

[] Run fewer years in the tergm, maybe 3 to 4, an early and a late
    - Fit one model for end, another for begging, 
    - slice smaller on periods of 2 yrs (possibly improvements on computation time)
    - must include all same nodes over the observation periods. Include term for `isolates` ~ could be difficult for model to fit. Isolates might be biasing the degree distributions.

[] `b2nodematch` give us the homophily term with diff = TRUE, this one ignores the b1mode. If 2 nodes on b2 match on the attribute, do they tie to the same node on b1 (municipalities). Test as replacement for `b2starmix`

    Error: 
Error in ergm.MCMLE(init, s, s.obs, control = control, verbose = verbose,  : 
  Number of edges in a simulated network exceeds that in the observed by a factor of more than 20. This is a strong indicator of model degeneracy or a very poor starting parameter configuration. If you are reasonably certain that neither of these is the case, increase the MCMLE.density.guard control.ergm() parameter.
In addition: Warning message:
In NetSeries(nw, times, NA.impute = control$CMLE.NA.impute) :
  Active vertex set varies from time point to time point. Estimation may not work.


```{}
> summary(mod1)
Call:
tergm(formula = dnet ~ Form(~edges + b2star(k = 2, attr = "cat_commit") + 
    b2cov("countries") + b2cov("buyers") + b1cov("prop_commit") * 
    b2cov("risk") + b1cov("soy") + b2cov("prop_commit") * b1cov("risk") + 
    b2cov("soy")) + Persist(~edges + b2star(k = 2, attr = "cat_commit") + 
    b2cov("countries") + b2cov("buyers") + b1cov("prop_commit") * 
    b2cov("risk") + b1cov("soy") + b2cov("prop_commit") * b1cov("risk") + 
    b2cov("soy")), estimate = "CMLE", times = 1:3)

Monte Carlo Conditional Maximum Likelihood Results:

                                          Estimate Std. Error MCMC %  z value Pr(>|z|)    
Form(1)~edges                           -7.1218176  0.0362273      0 -196.587  < 1e-04 ***
Form(1)~b2star2.cat_commit               0.0052657  0.0001111      0   47.404  < 1e-04 ***
Form(1)~b2cov.countries                  0.0101696  0.0012983      0    7.833  < 1e-04 ***
Form(1)~b2cov.buyers                    -0.0042062  0.0047813      0   -0.880 0.379008    
Form(1)~b1cov.prop_commit               -0.0386572  0.0291969      0   -1.324 0.185498    
Form(1)~b2cov.risk                       0.2432324  0.0095459      0   25.480  < 1e-04 ***
Form(1)~b1cov.prop_commit:b2cov.risk    -0.0469148  0.0065810      0   -7.129  < 1e-04 ***
Form(1)~b1cov.soy                        0.2860142  0.0101256      0   28.247  < 1e-04 ***
Form(1)~b2cov.prop_commit                0.7986872  0.0516753      0   15.456  < 1e-04 ***
Form(1)~b1cov.risk                       0.0897329  0.0057471      0   15.614  < 1e-04 ***
Form(1)~b2cov.prop_commit:b1cov.risk    -0.1039600  0.0149309      0   -6.963  < 1e-04 ***
Form(1)~b2cov.soy                       -0.0481240  0.0114267      0   -4.212  < 1e-04 ***
Persist(1)~edges                        -4.1843525  0.1138925      0  -36.739  < 1e-04 ***
Persist(1)~b2star2.cat_commit            0.0122678  0.0002747      0   44.665  < 1e-04 ***
Persist(1)~b2cov.countries              -0.0076052  0.0022499      0   -3.380 0.000724 ***
Persist(1)~b2cov.buyers                  0.0018566  0.0102158      0    0.182 0.855787    
Persist(1)~b1cov.prop_commit            -0.1623530  0.1020539      0   -1.591 0.111642    
Persist(1)~b2cov.risk                    0.0323884  0.0154778      0    2.093 0.036387 *  
Persist(1)~b1cov.prop_commit:b2cov.risk  0.0021861  0.0136814      0    0.160 0.873049    
Persist(1)~b1cov.soy                     0.2314699  0.0205723      0   11.252  < 1e-04 ***
Persist(1)~b2cov.prop_commit             0.1733725  0.0953840      0    1.818 0.069121 .  
Persist(1)~b1cov.risk                    0.0735311  0.0138238      0    5.319  < 1e-04 ***
Persist(1)~b2cov.prop_commit:b1cov.risk -0.0075720  0.0223185      0   -0.339 0.734406    
Persist(1)~b2cov.soy                     0.1942276  0.0249625      0    7.781  < 1e-04 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

     Null Deviance: 3928525  on 2833832  degrees of freedom
 Residual Deviance:  127678  on 2833808  degrees of freedom
 
AIC: 127726  BIC: 128035  (Smaller is better. MC Std. Err. = 6.495)


> summary(mod2)
Call:
tergm(formula = dnet ~ Form(~edges + gwb2degree(fixed = TRUE, 
    decay = 2.85) + b2star(k = 2, attr = "cat_commit") + b2cov("countries") + 
    b2cov("buyers") + b1cov("prop_commit") * b2cov("risk") + 
    b1cov("soy") + b2cov("prop_commit") * b1cov("risk") + b2cov("soy")) + 
    Persist(~edges + gwb2degree(fixed = TRUE, decay = 2.85) + 
        b2star(k = 2, attr = "cat_commit") + b2cov("countries") + 
        b2cov("buyers") + b1cov("prop_commit") * b2cov("risk") + 
        b1cov("soy") + b2cov("prop_commit") * b1cov("risk") + 
        b2cov("soy")), estimate = "CMLE", times = 1:3)

Monte Carlo Conditional Maximum Likelihood Results:

                                          Estimate Std. Error MCMC %  z value Pr(>|z|)    
Form(1)~edges                           -5.5870424  0.0332922      0 -167.818  < 1e-04 ***
Form(1)~gwb2deg.fixed.2.85              -3.6318300  0.0385029      0  -94.326  < 1e-04 ***
Form(1)~b2star2.cat_commit               0.0044367  0.0001097      0   40.437  < 1e-04 ***
Form(1)~b2cov.countries                  0.0172886  0.0015020      0   11.510  < 1e-04 ***
Form(1)~b2cov.buyers                    -0.0379250  0.0057146      0   -6.637  < 1e-04 ***
Form(1)~b1cov.prop_commit                0.0892602  0.0288128      0    3.098  0.00195 ** 
Form(1)~b2cov.risk                       0.1004388  0.0073261      0   13.710  < 1e-04 ***
Form(1)~b1cov.prop_commit:b2cov.risk    -0.0537177  0.0055781      0   -9.630  < 1e-04 ***
Form(1)~b1cov.soy                        0.2899330  0.0086038      0   33.698  < 1e-04 ***
Form(1)~b2cov.prop_commit                0.4336603  0.0455930      0    9.512  < 1e-04 ***
Form(1)~b1cov.risk                       0.0922925  0.0053040      0   17.400  < 1e-04 ***
Form(1)~b2cov.prop_commit:b1cov.risk    -0.1036894  0.0127140      0   -8.156  < 1e-04 ***
Form(1)~b2cov.soy                       -0.0504427  0.0095957      0   -5.257  < 1e-04 ***
Persist(1)~edges                        -2.5675536  0.0906387      0  -28.327  < 1e-04 ***
Persist(1)~gwb2deg.fixed.2.85           -3.1324113  0.0664676      0  -47.127  < 1e-04 ***
Persist(1)~b2star2.cat_commit            0.0063975  0.0005315      0   12.036  < 1e-04 ***
Persist(1)~b2cov.countries               0.0033857  0.0019680      0    1.720  0.08537 .  
Persist(1)~b2cov.buyers                  0.0289807  0.0068524      0    4.229  < 1e-04 ***
Persist(1)~b1cov.prop_commit            -0.1408049  0.0898857      0   -1.566  0.11723    
Persist(1)~b2cov.risk                   -0.1049263  0.0154312      0   -6.800  < 1e-04 ***
Persist(1)~b1cov.prop_commit:b2cov.risk -0.0088525  0.0125818      0   -0.704  0.48168    
Persist(1)~b1cov.soy                     0.2644201  0.0175355      0   15.079  < 1e-04 ***
Persist(1)~b2cov.prop_commit            -0.4456116  0.0692742      0   -6.433  < 1e-04 ***
Persist(1)~b1cov.risk                    0.1223195  0.0115622      0   10.579  < 1e-04 ***
Persist(1)~b2cov.prop_commit:b1cov.risk -0.0294775  0.0172190      0   -1.712  0.08691 .  
Persist(1)~b2cov.soy                     0.1685006  0.0199551      0    8.444  < 1e-04 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

     Null Deviance: 3928525  on 2833832  degrees of freedom
 Residual Deviance:  114580  on 2833806  degrees of freedom
 
AIC: 114632  BIC: 114966  (Smaller is better. MC Std. Err. = 5.995)

> summary(mod3)
Call:
tergm(formula = dnet ~ Form(~edges + gwb2degree(fixed = TRUE, 
    decay = 2.85) + isolates() + b2star(k = 2, attr = "cat_commit") + 
    b2cov("countries") + b2cov("buyers") + b1cov("prop_commit") * 
    b2cov("risk") + b1cov("soy") + b2cov("prop_commit") * b1cov("risk") + 
    b2cov("soy")) + Persist(~edges + gwb2degree(fixed = TRUE, 
    decay = 2.85) + isolates() + b2star(k = 2, attr = "cat_commit") + 
    b2cov("countries") + b2cov("buyers") + b1cov("prop_commit") * 
    b2cov("risk") + b1cov("soy") + b2cov("prop_commit") * b1cov("risk") + 
    b2cov("soy")), estimate = "CMLE", times = 1:3)

Monte Carlo Conditional Maximum Likelihood Results:

                                          Estimate Std. Error MCMC % z value Pr(>|z|)    
Form(1)~edges                           -5.2101846  0.0600754      0 -86.727  < 1e-04 ***
Form(1)~gwb2deg.fixed.2.85              -2.8334725  0.0719273      0 -39.394  < 1e-04 ***
Form(1)~isolates                         3.4958570  0.1271310      0  27.498  < 1e-04 ***
Form(1)~b2star2.cat_commit               0.0046510  0.0002247      0  20.696  < 1e-04 ***
Form(1)~b2cov.countries                  0.0178223  0.0027936      0   6.380  < 1e-04 ***
Form(1)~b2cov.buyers                    -0.0355314  0.0084458      0  -4.207  < 1e-04 ***
Form(1)~b1cov.prop_commit                0.1638040  0.0472903      0   3.464 0.000533 ***
Form(1)~b2cov.risk                       0.1203615  0.0126691      0   9.500  < 1e-04 ***
Form(1)~b1cov.prop_commit:b2cov.risk    -0.0552821  0.0100363      0  -5.508  < 1e-04 ***
Form(1)~b1cov.soy                        0.2050721  0.0157303      0  13.037  < 1e-04 ***
Form(1)~b2cov.prop_commit                0.4793623  0.0786536      0   6.095  < 1e-04 ***
Form(1)~b1cov.risk                       0.0932330  0.0087579      0  10.646  < 1e-04 ***
Form(1)~b2cov.prop_commit:b1cov.risk    -0.1066485  0.0264655      0  -4.030  < 1e-04 ***
Form(1)~b2cov.soy                       -0.0749361  0.0164589      0  -4.553  < 1e-04 ***
Persist(1)~edges                        -1.3971885  0.1040222      0 -13.432  < 1e-04 ***
Persist(1)~gwb2deg.fixed.2.85           -2.4810505  0.1156358      0 -21.456  < 1e-04 ***
Persist(1)~isolates                      3.7442153  0.1331748      0  28.115  < 1e-04 ***
Persist(1)~b2star2.cat_commit            0.0102863  0.0003459      0  29.736  < 1e-04 ***
Persist(1)~b2cov.countries               0.0136558  0.0038659      0   3.532 0.000412 ***
Persist(1)~b2cov.buyers                  0.0226012  0.0096984      0   2.330 0.019784 *  
Persist(1)~b1cov.prop_commit             0.2542213  0.1339743      0   1.898 0.057757 .  
Persist(1)~b2cov.risk                   -0.1148230  0.0221191      0  -5.191  < 1e-04 ***
Persist(1)~b1cov.prop_commit:b2cov.risk -0.0147183  0.0205553      0  -0.716 0.473968    
Persist(1)~b1cov.soy                     0.0495229  0.0167567      0   2.955 0.003123 ** 
Persist(1)~b2cov.prop_commit            -0.1284645  0.1294994      0  -0.992 0.321193    
Persist(1)~b1cov.risk                    0.0865121  0.0164807      0   5.249  < 1e-04 ***
Persist(1)~b2cov.prop_commit:b1cov.risk -0.1208277  0.0329184      0  -3.671 0.000242 ***
Persist(1)~b2cov.soy                     0.1812585  0.0247046      0   7.337  < 1e-04 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

     Null Deviance: 3928525  on 2833832  degrees of freedom
 Residual Deviance:  110002  on 2833804  degrees of freedom
 
AIC: 110058  BIC: 110418  (Smaller is better. MC Std. Err. = 25.78)
```


mod1 took 2.5 days on laptop, 186Mb, while mod2 took 9hrs on SRC server 352Mb
mod3 took 18hrs on server, 352Mb


`mcmc.diagnostics(mod3)` are not perfect but in general zero mean and normally distributed.
Some terms have tiny bimodal distributions (e.g. gw2deg), and some chains look like
random walks (e.g. b2start2.cat_commit). There is a little bit of skewness in terms like
b1cov.soy, b1cov.risk, or b2cov.prop_commit. But I believe the fit is decent.

## Meeting 20251020

[] Recode cat_commit not with an NA but with with a level == 0

**Failing:**
Warning: Model statistics ‘gwb2dsp.fixed.0.75’ are linear combinations of some set of preceding statistics at the current stage of the estimation. This may indicate that the model is nonidentifiable.
1 Optimizing with step length 0.0011.
The log-likelihood improved by 26910233150504426274816.0000.
Estimating equations are not within tolerance region.
Iteration 3 of at most 60:
Error in ergm.MCMLE(init, s, s.obs, control = control, verbose = verbose,  : 
  Number of edges in a simulated network exceeds that in the observed by a factor of more than 20. This is a strong indicator of model degeneracy or a very poor starting parameter configuration. If you are reasonably certain that neither of these is the case, increase the MCMLE.density.guard control.ergm() parameter.
In addition: Warning messages:
1: In ergm_MCMC_sample(s, control, theta = mcmc.init, verbose = max(verbose -  :
  Unable to reach target ESS in iterations alotted.
2: In ergm_MCMC_sample(s, control, theta = mcmc.init, verbose = max(verbose -  :
  Unable to reach target ESS in iterations alotted.

[] How do we deal with time: before / after implementation of the legislation.
Do not use the tergm in all years. Use the tergms to explore the idea of stickyness

- How commitments change over time, compute for exploration: commitments per year
- Persistence side of eq is what controls for stickyness 
- use the same formula for the Formation and Persistence terms

Interpretations:
- gwb2dsp: centered on companies, it measures the tendency of companies to share the same municipalities
- negative sign means they tend to share centrality.

## Meeting 20250829

[X] Replace cat_commit for municipalities with NAs, and then run b1starmix because we want it centered on municipalities. It should read:
> b2starmix.2.cat_commit.NA.high   b2starmix.2.cat_commit.NA.low 

> Done but it doesn't work due to Error: In term ‘b2starmix’ in package ‘ergm’: Attribute ‘"cat_commit"’ has missing data, which is not currently supported by ergm

[X] Use the gw1degree on municipalities. make sure to explore the decay on a short ergm.

Call:
ergm(formula = net[[8]] ~ edges + b2cov("countries") + b2cov("buyers") + 
    b1cov("prop_commit") * b2cov("risk") + b1cov("soy") + b2cov("prop_commit") * 
    b1cov("risk") + b2cov("soy") + gwb1degree(fixed = TRUE, decay = 0.6) + 
    edgecov(as.sociomatrix(net[[1]]), attrname = "past_net") + 
    gwb2dsp(fixed = TRUE, decay = 0.75), control = control.ergm(parallel = 10, 
    parallel.type = "PSOCK", MPLE.maxit = 5))

Monte Carlo Maximum Likelihood Results:

                               Estimate Std. Error MCMC %  z value Pr(>|z|)    
edges                        -1.182e+01  1.086e-01      0 -108.759  < 1e-04 ***
b2cov.countries              -2.756e-02  1.184e-03      0  -23.280  < 1e-04 ***
b2cov.buyers                  3.665e-03  4.792e-04      0    7.648  < 1e-04 ***
b1cov.prop_commit            -1.228e+00  5.321e-02      0  -23.080  < 1e-04 ***
b2cov.risk                    6.277e-02  7.957e-03      0    7.888  < 1e-04 ***
b1cov.prop_commit:b2cov.risk  1.100e-01  8.528e-03      0   12.896  < 1e-04 ***
b1cov.soy                     1.005e+00  2.201e-02      0   45.655  < 1e-04 ***
b2cov.prop_commit             6.782e-01  3.355e-02      0   20.214  < 1e-04 ***
b1cov.risk                    3.699e-02  5.264e-03      0    7.027  < 1e-04 ***
b2cov.prop_commit:b1cov.risk -4.075e-02  9.071e-03      0   -4.492  < 1e-04 ***
b2cov.soy                     9.345e-01  1.911e-02      0   48.898  < 1e-04 ***
gwb1deg.fixed.0.6            -1.287e+00  8.681e-02      0  -14.825  < 1e-04 ***
edgecov.past_net              1.049e+00  6.803e-02      0   15.416  < 1e-04 ***
gwb2dsp.fixed.0.75           -1.620e-02  5.062e-03      0   -3.200  0.00137 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

     Null Deviance: 1964263  on 1416916  degrees of freedom
 Residual Deviance:   86511  on 1416902  degrees of freedom
 
AIC: 86539  BIC: 86709  (Smaller is better. MC Std. Err. = 0.5941)

[] another option to run the multiple year term is using the stergm command.

[] once the model is working for the full network over time, replicate the cerrado vs non-cerrado comparison.

## Meeting 20250226

[x] Add the gwdegree terms (this should help with convergence)
    - The interpretation of this term is not that they just have more ties, but it’s often called an ‘anti-preferential attachment’ term. If negative, it means that locations/producers that have ties tend in general to have more ties. If positive, it tends to show that there’s an even distribution of ties.
[] Run the gw2dp with the parameters suggested by Lorien to try to find a good decay for it
[x] Add the tergm term
[] At this point I think we should look at the output and decide whether we should add the b2starmix
[] Add b2startmix (if we decide is a good next step)
    - Warning!: b2starmix.2.prop_commit.1.0.997832300916454 are at their smallest attainable values. Their coefficients will be fixed at -Inf.
[] Discuss whether makes sense to do the stergm

## meeting 241216

- Entre mas agreements mas diversificacion de links: GWESP
- Interaction term between b1:b2
- un atributo que sea de los dos, normalizado por la media
    - % commitment
    - mean_risk
- difference entre los estadisticos que tienen las mismas unidades una vez estan normalizados.

## meeting 241112

- Re run same model with:
    - only cerrado and non-cerrado municipalities [done]
    - drop the area normalization so effects are a bit bigger but control for municipality area [done]
    - compare AIC to drop models with small coeffs that contracdict themselves.

## meeting 240609

- New strategy for interaction effect between risk and commitment. Two options
    - Categorical: Define dummies with 1/0
    - Continuous:  % commitment vs normalized deforestation risk / area.
- Try linear regressions following lit review on homophily.

## Meeting 240404

- Viaje de Angela sirvio para fortalecer contactos con Selva y Smithsonian.

## Meeting 230427

- ergms with weighted, compare years [done without weights, ergm with weights do not converge]
- trajectories through time of companies in the soy / risk space [done]
- diff-in-diff for the treatment of signing agreement. You need companies wihtout agreement to test before / after [discussed: unlikely to work due to lack of matching, very few companies committed with features that are unique in the dataset (high export, high risk)]
- ergm term diff() commitment in company (1/0) - municipality normalized deforestation risk (0:1)

## Meeting 230425

Next steps:
- Correlations across years
- One-mode projection on municipalities and importing countries
- Calculate the stochastic block model, p_between vs p_intra
- Bipartite: bip ~ company_node_zdc + municipality_def_risk + comp_soy_tons +
prop_certified_soy + company_node_zdc * municiplatiy_def_risk

## Meeting 220215

Rodrigo Botero - Fundacion para el desarrollo sostenible FDS

- Good maps and on ground info
Vision Amazonia (payment schemes PES) - industry development

Andres Zuluaga (PhD with Etter): head of World Bank lead PES program for sustainable cattle ranching, working now with TNC

Tropenbos Colombia

Pastoral social (locally)

## Meeting 230130

- Read update lit on difference between difussion, contagion, and homophily. Make sure the ergm capture difussion. Test simple vs complex contagion
- Idea: model with weights -- do ppl with certification change their sourceing or prop of sourcing? (weighted ergm)
- Ho: Hi risk sites export less over time
- H0: Commited companies reduce risk exposure

When modeling weights you can assume fixed networks if the structure is not changing much over time. Derive correlation over time over different year / networks.
- Model flow with fixed network
- Assumption: If a compnay has one link with agreement, then the company has agreed (from there on).
- Bipartite from municipalities to exporting companies.
- For the dynamic contagion problem: is it temporal ergm or SAOM what we need?

## Readings

### Shalizi et al 2011 

**Homophily and contagion are generically confounded in observational social network studies** Sociological Methods & Research 40(2)

- _"Do they act similarly because they are close in the network, due to some form of influence that acts along network ties (or, as it is often suggestively put, ‘‘contagion’’1)? Or rather, are they close in the network because of these similarities, through the processes known as assortative mixing on traits, or more simply as homophily"_
- _"latent homophily and contagion are generically con- founded with each other (see the second section), and any direct contagion effects cannot be nonparametrically identified from observational data."_
- _" the effort may prove to be inadequate if any unobserved covariates have a part in both tie selection and in service adoption. This brings us to our fundamental point: To attempt to assign strengths to influence or contagion as opposed to homophily presupposes that the distinc- tion is identifiable, and there have been grounds to doubt this for some time."_
- _"We now show that in fact, contagion effects are nonparametrically un- identifiable in the presence of latent homophily—that there is just no way to separate selection from influence observationally."_
- _"the most successful attempts at explicit modeling that handle both homophily and influence, as found in the work of Leenders (2005) and Steglich, Snijders, and Pearson (2004), involve, all at once, strong parametric (exponential-family) assumptions, plus the assumption that observable covariates carry all of the dependence from X to Y and A; the latter is also implicitly assumed by the matching methods of Aral et al. (2009)."_

So ERGMs wont do to this problem, neither regression matching. Here is an option:

- _"By focusing on unreciprocated directed edges—pairs (i,j) where Aij = 1 but Aji = 0, so that j’s prior outcome can be said to influence i’s present, but not i’s prior outcome on j’s present—one can consider the distributions of the outcomes conditional on their partner’s pre- vious outcome, Yi(t)jYj(t - 1) and Yj(t)jYi(t - 1) (though other observable covariates [Zi, Zj] may also be conditioned on). An asymmetry here, revealed by the difference in the corresponding regression coefficients, might then be due to some influence being transmitted along the asymmetric edge, and not due to external common causes (e.g., a new fast food restaurant) or other behaviors attributable to latent characteristics... **it works as a test for direct influence in some models**."_

But they showed that under two conditions it breaks (model can't be trusted): first, influencers differ systematically in their values of X covariates; and second, different neighbourhoods of X have differetn local (linear) relationships to Y. 

- _" latent homophilous variables can produce a substantial apparent contagion effect, including the asymmetry expected of actual contagion."_

Then they go on testing another mechanism on a voter model, where people change relationships and opinions over time depending on their neighbourhood. Two communities emerge:

- _"On regular lattices, this mechanism causes the voter model to self-organize into spatially homogeneous domains, with slowly shifting boundaries between them...social type is an indirect cue to network neighborhood, and accordingly predicts choices"_
- _"individuals’ choices are not independent conditional on their traits, as is generally assumed in, for example, survey research; diffusion creates the observed dependence... differences in social types are at most related to differences in choices, not to the actual content of those choices."_

- _"we have shown that latent homophily togeth- er with causal effects from the homophilous trait cannot be readily distinguished, observationally, from contagion or influence, and that this remains true even if there is asymmetry between ‘‘senders’’ and ‘‘receivers’’ in the network."_
- _"we sketch three constructive responses that may be possible when dealing with network data where the causal structure is imperfectly understood or incompletely measured. These are to randomize over the network, place bounds on unidentifiable effects, and **use the division of the network into communities as a proxy for latent homophily.**"_

Randomize the network:

1. Divide the nodes into two groups, by assigning each node to one of two bins with equal probability; let these groups be labeled as J1 and J2.
2. Let YJ1 (t) be the vector-valued time series obtained by collecting each of the Yi (t) for i ∈ J1 into one object, and similarly for YJ2 (t).
3. Use some available mechanism to predict the time series for the first bin, YJ1 (t). from its lagged counterpart, YJ2 (t - 1), while controlling for the previous time point within the first half, YJ1 (t - 1).

- _"By repeating this procedure, then averaging over all iterations (producing new partitions each time), there will be a non-zero predictive ability if and only if there is actual contagion or influence"_

Bounds (but they do not elaborate, they propose for future research): 

- _"even when param- eters (e.g., the causal effect of Yj(t - 1) on Yi(t)) are observationally unidentifiable, the distribution of observations may suffice to bound the parameters...  If the bound on this effect excluded zero, that would show the observed association could not be due solely to homophily, but that some contagion must also be present."_

Network clustering:

- _" ‘‘Homophily’’ means simply that individuals tend to choose neighbors that resemble them; this tendency will be especially pronounced if pairs of neighbors also have other neighbors in common, since these pairings will also be driven by homophily. "_
- _"By the arguments we have presented so far, such control-by-clustering will generally be unable to eliminate the confounding.18 However, in conjunction with the bounds approach mentioned earlier, conditioning on estimated community memberships might still noticeably reduce the confounding. "_

### Shalizi and Rinaldo 2013
**Consistency under sampling of exponential random graph models** Annals of Statistics 41 (2) 508-535

- _"the parameter estimates obtained from a sub-network may not provide reliable estimates of, or may not even be relatable to, the parameters of the whole network, rendering the task of statistical inference based on a sub-network ill-posed. We formalize this question using the notion of “projective families” from the theory of stochastic processes. We say that a model is projective when the same parameters can be used for both the whole network and any of its sub-networks."_
- _"Typically, however, ERGMs are not dyadic independence models... Empirically, when using such specifications, one often finds a nontrivial coefficient for such “transitivity” or “clustering,” over and above homophily [26]. It is because of such findings that we ask whether the parameters in these models are projective"_
- _" Since these models are not projective, however, it is impossible to improve parameter estimates by getting more data, since parameters for smaller sub-graphs just cannot be extrapolated to larger graphs (or vice versa). We thus have a near-dichotomy for ERGMs. Dyadic independence models have separable and independent increments to the statistics, and the resulting family is projective. However, specifications where the sufficient statistics count larger motifs cannot have separable increments, and projectibility does not hold. Such an ERGM may provide a good description of a given social network on a certain set of nodes, but it cannot be projected to give predictions on any larger or more global graph from which that one was drawn."_
- _"Dyadic independence models are projective models, but are sociologically extremely implausible, and certainly do not manage to reproduce the data well. More interesting specifications, involving clustering terms, never have separable increments. We thus have an impasse which it seems can only be resolved by going to a different family of specifications. One possibility—which, however, requires more and different data—is to model the evolution of networks over time [58]."_

### McFowland and Shalizi
**Estimating causal peer influence in homophilous social networks by inferring latent locations** Journal of the American Statistical Association

- _"This homophily means that network neighbors are informative about latent qualities a node possesses, providing an alternative route by which a node’s behavior can be predicted from their neighbors."_

They present the equations of the ideal model, and the estimated model, where they use a community detection result to control for homophily. The estimated community is a proxy of the real community and residual unobserved co-variates. For the model to work, an assumption of independence needs to be fulfiled and discussed: that the covariates are ortogonal to the behaviour given the estimated community (see formula).

- _"There may be attributes that are incorporated into Ci which are relevant only to network ties, not behavior, and independent of the other attributes; these are of no concern to us, and can be regarded as part of the noise in the tie-formation process. Network models that satisfy this assumption—that is, that all ties are conditionally independent of each other given the latent variables for each node—are some- times called “graphons” or “w-random graphs” and are clearly exchangeable (permutation-invariant) over nodes." _
- _"if all the variables relevant to tie-formation and node behavior are observed, the ordinary least-square (OLS) estimator provides an unbiased estimate (βˆOLS) of β"_

